using System.Drawing;
using SpiceChecker.Models;
using ThemeDefinition = SpiceChecker.Models.AppTheme;

namespace SpiceChecker.Services
{
    public static class ThemeCatalog
    {
        public static ThemeDefinition GetTheme(ThemeId id) => id switch
        {
            ThemeId.Legacy95 => Legacy95(),
            ThemeId.LunaXP => LunaXP(),
            ThemeId.Aero7 => Aero7(),
            ThemeId.ModernLight => ModernLight(),
            ThemeId.ModernDark => ModernDark(),
            ThemeId.Fluent11Light => Fluent11Light(),
            ThemeId.Fluent11Dark => Fluent11Dark(),
            _ => Fluent11Dark()
        };

        private static ThemeDefinition Legacy95() => new()
        {
            Id = ThemeId.Legacy95,
            DisplayName = "Legacy 95",
            TitleBarColor = Color.FromArgb(0, 0, 128),
            TitleBarGradientEnd = Color.FromArgb(16, 132, 208),
            TitleBarHasGradient = true,
            TitleBarTextColor = Color.White,
            TitleBarFont = new Font("Arial", 8f, FontStyle.Bold),
            TitleBarHeight = 22,
            TitleButtonHoverBg = Color.FromArgb(180, 180, 180),
            TitleButtonsIsOldStyle = true,
            FormBackground = Color.FromArgb(192, 192, 192),
            ToolbarBackground = Color.FromArgb(192, 192, 192),
            FilterBarBackground = Color.FromArgb(192, 192, 192),
            GridBackground = Color.White,
            GridAlternateRow = Color.FromArgb(245, 245, 245),
            GridSelectionBackground = Color.FromArgb(0, 0, 128),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(192, 192, 192),
            GridHeaderForeground = Color.Black,
            TextColor = Color.Black,
            TextMutedColor = Color.FromArgb(80, 80, 80),
            BaseFont = new Font("MS Sans Serif", 8f),
            BorderColor = Color.FromArgb(128, 128, 128),
            HasOuterBorder3D = true,
            ButtonBackground = Color.FromArgb(192, 192, 192),
            ButtonForeground = Color.Black,
            ButtonBorder = Color.FromArgb(128, 128, 128),
            ButtonHover = Color.FromArgb(212, 212, 212),
            ButtonHas3DRelief = true,
            InputBackground = Color.White,
            InputForeground = Color.Black,
            InputBorder = Color.FromArgb(128, 128, 128),
            AccentColor = Color.FromArgb(0, 0, 128),
            SeparatorColor = Color.FromArgb(128, 128, 128)
        };

        private static ThemeDefinition LunaXP() => new()
        {
            Id = ThemeId.LunaXP,
            DisplayName = "Luna XP",
            TitleBarColor = Color.FromArgb(1, 84, 170),
            TitleBarGradientEnd = Color.FromArgb(166, 202, 240),
            TitleBarHasGradient = true,
            TitleBarTextColor = Color.White,
            TitleBarFont = new Font("Trebuchet MS", 9f, FontStyle.Bold),
            TitleBarHeight = 28,
            TitleButtonHoverBg = Color.FromArgb(100, 160, 220),
            TitleButtonsIsOldStyle = true,
            FormBackground = Color.FromArgb(236, 233, 216),
            ToolbarBackground = Color.FromArgb(245, 244, 234),
            FilterBarBackground = Color.FromArgb(236, 233, 216),
            GridBackground = Color.White,
            GridAlternateRow = Color.FromArgb(240, 248, 255),
            GridSelectionBackground = Color.FromArgb(49, 106, 197),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(214, 223, 247),
            GridHeaderForeground = Color.FromArgb(0, 30, 100),
            TextColor = Color.Black,
            TextMutedColor = Color.FromArgb(90, 90, 90),
            BaseFont = new Font("Tahoma", 8f),
            BorderColor = Color.FromArgb(122, 150, 223),
            HasOuterBorder3D = false,
            ButtonBackground = Color.FromArgb(240, 240, 232),
            ButtonForeground = Color.Black,
            ButtonBorder = Color.FromArgb(0, 60, 160),
            ButtonHover = Color.FromArgb(200, 220, 248),
            ButtonHas3DRelief = false,
            InputBackground = Color.White,
            InputForeground = Color.Black,
            InputBorder = Color.FromArgb(127, 157, 185),
            AccentColor = Color.FromArgb(49, 106, 197),
            SeparatorColor = Color.FromArgb(122, 150, 223)
        };

        private static ThemeDefinition Aero7() => new()
        {
            Id = ThemeId.Aero7,
            DisplayName = "Aero 7",
            TitleBarColor       = Color.FromArgb(181, 206, 235),
            TitleBarGradientEnd = Color.FromArgb(204, 223, 245),
            TitleBarHasGradient = true,
            TitleBarTextColor   = Color.FromArgb(15, 15, 15),
            TitleBarFont        = new Font("Segoe UI", 9f, FontStyle.Regular),
            TitleBarHeight      = 30,
            TitleButtonHoverBg  = Color.FromArgb(180, 210, 240),
            TitleButtonsIsOldStyle = false,
            FormBackground      = Color.FromArgb(240, 240, 240),
            ToolbarBackground   = Color.FromArgb(238, 244, 252),
            FilterBarBackground = Color.FromArgb(245, 249, 255),
            GridBackground      = Color.White,
            GridAlternateRow    = Color.FromArgb(240, 248, 255),
            GridSelectionBackground = Color.FromArgb(51, 102, 204),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(212, 228, 244),
            GridHeaderForeground = Color.FromArgb(30, 57, 91),
            TextColor           = Color.FromArgb(20, 20, 20),
            TextMutedColor      = Color.FromArgb(90, 110, 135),
            BaseFont            = new Font("Segoe UI", 9f),
            BorderColor         = Color.FromArgb(155, 191, 228),
            HasOuterBorder3D    = false,
            ButtonBackground    = Color.FromArgb(225, 237, 251),
            ButtonForeground    = Color.FromArgb(20, 20, 20),
            ButtonBorder        = Color.FromArgb(120, 174, 229),
            ButtonHover         = Color.FromArgb(190, 220, 250),
            ButtonHas3DRelief   = false,
            InputBackground     = Color.White,
            InputForeground     = Color.Black,
            InputBorder         = Color.FromArgb(130, 180, 225),
            AccentColor         = Color.FromArgb(51, 102, 204),
            SeparatorColor      = Color.FromArgb(155, 191, 228),
            Backdrop            = BackdropEffect.Acrylic,
            BackdropFallbackTint = Color.FromArgb(160, 0, 80, 160)
        };

        private static ThemeDefinition ModernLight() => new()
        {
            Id = ThemeId.ModernLight,
            DisplayName = "Modern (clair)",
            TitleBarColor = Color.White,
            TitleBarGradientEnd = Color.White,
            TitleBarHasGradient = false,
            TitleBarTextColor = Color.Black,
            TitleBarFont = new Font("Segoe UI", 9f, FontStyle.Regular),
            TitleBarHeight = 32,
            TitleButtonHoverBg = Color.FromArgb(230, 230, 230),
            TitleButtonsIsOldStyle = false,
            FormBackground = Color.White,
            ToolbarBackground = Color.FromArgb(243, 243, 243),
            FilterBarBackground = Color.FromArgb(250, 250, 250),
            GridBackground = Color.White,
            GridAlternateRow = Color.FromArgb(248, 248, 248),
            GridSelectionBackground = Color.FromArgb(0, 120, 215),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(243, 243, 243),
            GridHeaderForeground = Color.Black,
            TextColor = Color.Black,
            TextMutedColor = Color.FromArgb(100, 100, 100),
            BaseFont = new Font("Segoe UI", 9f),
            BorderColor = Color.FromArgb(217, 217, 217),
            HasOuterBorder3D = false,
            ButtonBackground = Color.FromArgb(230, 230, 230),
            ButtonForeground = Color.Black,
            ButtonBorder = Color.FromArgb(180, 180, 180),
            ButtonHover = Color.FromArgb(204, 228, 247),
            ButtonHas3DRelief = false,
            InputBackground = Color.White,
            InputForeground = Color.Black,
            InputBorder = Color.FromArgb(170, 170, 170),
            AccentColor = Color.FromArgb(0, 120, 215),
            SeparatorColor = Color.FromArgb(217, 217, 217)
        };

        private static ThemeDefinition ModernDark() => new()
        {
            Id = ThemeId.ModernDark,
            DisplayName = "Modern (sombre)",
            TitleBarColor = Color.FromArgb(31, 31, 31),
            TitleBarGradientEnd = Color.FromArgb(31, 31, 31),
            TitleBarHasGradient = false,
            TitleBarTextColor = Color.White,
            TitleBarFont = new Font("Segoe UI", 9f, FontStyle.Regular),
            TitleBarHeight = 32,
            TitleButtonHoverBg = Color.FromArgb(55, 55, 55),
            TitleButtonsIsOldStyle = false,
            FormBackground = Color.FromArgb(31, 31, 31),
            ToolbarBackground = Color.FromArgb(38, 38, 38),
            FilterBarBackground = Color.FromArgb(45, 45, 45),
            GridBackground = Color.FromArgb(28, 28, 28),
            GridAlternateRow = Color.FromArgb(35, 35, 35),
            GridSelectionBackground = Color.FromArgb(0, 102, 204),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(50, 50, 50),
            GridHeaderForeground = Color.White,
            TextColor = Color.White,
            TextMutedColor = Color.FromArgb(180, 180, 180),
            BaseFont = new Font("Segoe UI", 9f),
            BorderColor = Color.FromArgb(70, 70, 70),
            HasOuterBorder3D = false,
            ButtonBackground = Color.FromArgb(50, 50, 50),
            ButtonForeground = Color.White,
            ButtonBorder = Color.FromArgb(80, 80, 80),
            ButtonHover = Color.FromArgb(70, 70, 70),
            ButtonHas3DRelief = false,
            InputBackground = Color.FromArgb(45, 45, 45),
            InputForeground = Color.White,
            InputBorder = Color.FromArgb(80, 80, 80),
            AccentColor = Color.FromArgb(0, 120, 215),
            SeparatorColor = Color.FromArgb(70, 70, 70),
            Backdrop = BackdropEffect.Acrylic,
            BackdropFallbackTint = Color.FromArgb(200, 20, 20, 20)
        };

        private static ThemeDefinition Fluent11Light() => new()
        {
            Id = ThemeId.Fluent11Light,
            DisplayName = "Fluent 11 (clair)",
            TitleBarColor       = Color.FromArgb(243, 243, 243),
            TitleBarGradientEnd = Color.FromArgb(243, 243, 243),
            TitleBarHasGradient = false,
            TitleBarTextColor   = Color.FromArgb(28, 28, 28),
            TitleBarFont        = new Font("Segoe UI Variable", 9f),
            TitleBarHeight      = 32,
            TitleButtonHoverBg  = Color.FromArgb(218, 218, 218),
            TitleButtonsIsOldStyle = false,
            FormBackground      = Color.FromArgb(249, 249, 249),
            ToolbarBackground   = Color.FromArgb(243, 243, 243),
            FilterBarBackground = Color.FromArgb(249, 249, 249),
            GridBackground      = Color.FromArgb(255, 255, 255),
            GridAlternateRow    = Color.FromArgb(246, 246, 246),
            GridSelectionBackground = Color.FromArgb(0, 103, 192),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(238, 238, 238),
            GridHeaderForeground = Color.FromArgb(28, 28, 28),
            TextColor           = Color.FromArgb(28, 28, 28),
            TextMutedColor      = Color.FromArgb(96, 96, 96),
            BaseFont            = new Font("Segoe UI Variable", 9f),
            BorderColor         = Color.FromArgb(224, 224, 224),
            HasOuterBorder3D    = false,
            ButtonBackground    = Color.FromArgb(254, 254, 254),
            ButtonForeground    = Color.FromArgb(28, 28, 28),
            ButtonBorder        = Color.FromArgb(199, 199, 199),
            ButtonHover         = Color.FromArgb(232, 232, 232),
            ButtonHas3DRelief   = false,
            InputBackground     = Color.White,
            InputForeground     = Color.FromArgb(28, 28, 28),
            InputBorder         = Color.FromArgb(199, 199, 199),
            AccentColor         = Color.FromArgb(0, 103, 192),
            SeparatorColor      = Color.FromArgb(224, 224, 224),
            Backdrop            = BackdropEffect.Mica,
            BackdropFallbackTint = Color.FromArgb(180, 240, 240, 240)
        };

        private static ThemeDefinition Fluent11Dark() => new()
        {
            Id = ThemeId.Fluent11Dark,
            DisplayName = "Fluent 11 (sombre)",
            TitleBarColor       = Color.FromArgb(32, 32, 32),
            TitleBarGradientEnd = Color.FromArgb(32, 32, 32),
            TitleBarHasGradient = false,
            TitleBarTextColor   = Color.FromArgb(255, 255, 255),
            TitleBarFont        = new Font("Segoe UI Variable", 9f),
            TitleBarHeight      = 32,
            TitleButtonHoverBg  = Color.FromArgb(58, 58, 58),
            TitleButtonsIsOldStyle = false,
            FormBackground      = Color.FromArgb(32, 32, 32),
            ToolbarBackground   = Color.FromArgb(40, 40, 40),
            FilterBarBackground = Color.FromArgb(44, 44, 44),
            GridBackground      = Color.FromArgb(28, 28, 28),
            GridAlternateRow    = Color.FromArgb(37, 37, 37),
            GridSelectionBackground = Color.FromArgb(0, 103, 192),
            GridSelectionForeground = Color.White,
            GridHeaderBackground = Color.FromArgb(52, 52, 52),
            GridHeaderForeground = Color.FromArgb(214, 214, 214),
            TextColor           = Color.FromArgb(220, 220, 220),
            TextMutedColor      = Color.FromArgb(144, 144, 144),
            BaseFont            = new Font("Segoe UI Variable", 9f),
            BorderColor         = Color.FromArgb(62, 62, 62),
            HasOuterBorder3D    = false,
            ButtonBackground    = Color.FromArgb(50, 50, 50),
            ButtonForeground    = Color.FromArgb(220, 220, 220),
            ButtonBorder        = Color.FromArgb(72, 72, 72),
            ButtonHover         = Color.FromArgb(64, 64, 64),
            ButtonHas3DRelief   = false,
            InputBackground     = Color.FromArgb(48, 48, 48),
            InputForeground     = Color.FromArgb(220, 220, 220),
            InputBorder         = Color.FromArgb(72, 72, 72),
            AccentColor         = Color.FromArgb(96, 205, 255),
            SeparatorColor      = Color.FromArgb(62, 62, 62),
            Backdrop            = BackdropEffect.Mica,
            BackdropFallbackTint = Color.FromArgb(200, 32, 32, 32)
        };
    }
}
